# Generated by Django 4.2.4 on 2023-11-30 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('nombre_comuna', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, primary_key=True, serialize=False, verbose_name='Género')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripcion de la mascota')),
                ('caracteristicas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Caracteristicas de la mascota')),
                ('edad_est', models.IntegerField(verbose_name='Edad estimada de la mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('nombre_org', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre de la organizacion')),
                ('tipo_organizacion', models.CharField(max_length=50, verbose_name='Tipo de Organizacion')),
                ('logo_org', models.ImageField(upload_to='logo', verbose_name='Logo de la Organizacion')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion de la Organizacion')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('nombre_region', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, primary_key=True, serialize=False, verbose_name='Género')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_veterinario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Centro veterinario')),
                ('medico_veterinario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Medico veterinario')),
                ('diagnostico', models.TextField(verbose_name='Diagnostico del seguimiento')),
                ('receta', models.CharField(max_length=200, verbose_name='Receta de la visita')),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('tipo_nombre', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, primary_key=True, serialize=False, verbose_name='Tipo de mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='RUT')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, verbose_name='Género')),
                ('role', models.CharField(choices=[('P', 'Postulante'), ('E', 'Empleador')], max_length=10, verbose_name='Rol de usuario')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.comuna')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Verificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ver', models.CharField(choices=[('O', 'Online'), ('P', 'Presencial')], max_length=20)),
                ('descripcion', models.TextField(verbose_name='Descripcion de la verificacion')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de la verificacion')),
                ('vigencia_animal', models.BooleanField(blank=True, null=True, verbose_name='Debe ser devuelto o no')),
                ('nombre_org', models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='adopciones.organizacion', verbose_name='Nombre de la organizacion')),
                ('rut', models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='adopciones.usuario', verbose_name='RUT del dueño')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('tipo_vacuna', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de vacuna')),
                ('vigencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vigencia de la vacuna (meses o años)')),
                ('id_seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.seguimiento')),
            ],
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='rut',
            field=models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='adopciones.usuario', verbose_name='RUT del dueño'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='nombre_org',
            field=models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='adopciones.organizacion', verbose_name='Nombre de la organizacion'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='rut',
            field=models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='adopciones.usuario', verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tipo_nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.tipomascota'),
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_mascota', models.ImageField(upload_to='mascota', verbose_name='Imagen de la mascota')),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.mascota')),
            ],
        ),
    ]
