# Generated by Django 4.2.4 on 2023-12-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_colecta', models.CharField(max_length=50, verbose_name='Nombre de la colecta')),
                ('descripcion_colecta', models.TextField()),
                ('rut', models.CharField(max_length=12, verbose_name='RUT de la cuenta')),
                ('banco', models.CharField(max_length=50)),
                ('acc_type', models.CharField(choices=[('C', 'Cuenta corriente'), ('V', 'Cuenta vista'), ('A', 'Cuenta de ahorro')], max_length=50)),
                ('num_cuenta', models.CharField(max_length=50, verbose_name='Numero de la cuenta')),
                ('monto_inicial', models.IntegerField(verbose_name='Monto inicial de colecta (0)')),
                ('nombre_org', models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='adopciones.organizacion', verbose_name='Nombre de la organizacion')),
            ],
        ),
    ]
