# Generated by Django 4.2.4 on 2023-12-27 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d3_dpa_chile', '0002_alter_comuna_codigo_alter_provincia_codigo_and_more'),
        ('adopciones', '0002_colecta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d3_dpa_chile.comuna'),
        ),
        migrations.AlterField(
            model_name='tipomascota',
            name='tipo_nombre',
            field=models.CharField(choices=[('P', 'Perro'), ('G', 'Gato'), ('O', 'Otro')], max_length=10, primary_key=True, serialize=False, verbose_name='Tipo de mascota'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d3_dpa_chile.comuna'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('A', 'Adoptante'), ('O', 'Organizacion')], max_length=10, verbose_name='Rol de usuario'),
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
    ]
