# Generated by Django 4.2.4 on 2023-12-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0003_delete_region_alter_organizacion_comuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='contacto',
            field=models.CharField(default='+569', max_length=25, verbose_name='telefono de contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='fecha',
            field=models.DateField(null=True, verbose_name='Fecha del seguimiento'),
        ),
        migrations.AlterField(
            model_name='colecta',
            name='descripcion_colecta',
            field=models.TextField(verbose_name='Descripcion de la colecta'),
        ),
    ]
