# Generated by Django 4.2.4 on 2023-12-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0005_remove_organizacion_comuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='correo',
            field=models.CharField(default='correodefault@gmail.com', max_length=50, verbose_name='Correo de contacto de la organizacion'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='contacto',
            field=models.CharField(default='+569', max_length=25, verbose_name='Telefono de contacto de la organizacion'),
        ),
    ]
