# Generated by Django 4.2.4 on 2023-12-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0006_organizacion_correo_alter_organizacion_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='logo_org',
            field=models.ImageField(blank=True, upload_to='logo', verbose_name='Logo de la Organizacion'),
        ),
    ]
