# Generated by Django 4.2.4 on 2023-12-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0008_alter_mascota_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedeorganizacion',
            name='contacto',
            field=models.CharField(default='+569', max_length=25, verbose_name='Telefono de contacto de la sede'),
        ),
    ]
