# Generated by Django 4.2.4 on 2023-12-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0009_sedeorganizacion_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='img_mascota',
            field=models.ImageField(upload_to='Img_mascotas', verbose_name='Imagen de la mascota'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='logo_org',
            field=models.ImageField(blank=True, upload_to='logos_org', verbose_name='Logo de la Organizacion'),
        ),
    ]
