# Generated by Django 4.2.4 on 2023-12-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0010_alter_imagen_img_mascota_alter_organizacion_logo_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='caracteristicas',
        ),
        migrations.AddField(
            model_name='mascota',
            name='soc_1',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No'), ('N/A', 'No se sabe')], default='N/A', max_length=25, verbose_name='Sociable con niños'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='soc_2',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No'), ('N/A', 'No se sabe')], default='N/A', max_length=25, verbose_name='Sociable con perros'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='soc_3',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No'), ('N/A', 'No se sabe')], default='N/A', max_length=25, verbose_name='Sociable con gatos'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tamano',
            field=models.CharField(choices=[('S', 'Pequeño'), ('L', 'Grande'), ('M', 'Mediano')], default='S', max_length=25, verbose_name='Tamaño de la mascota'),
        ),
    ]
