# Generated by Django 4.2.4 on 2023-12-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0011_remove_mascota_caracteristicas_mascota_soc_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuna',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vacunacion'),
        ),
    ]
