# Generated by Django 4.2.4 on 2023-12-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0013_remove_mascota_nombre_org_mascota_sede_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='receta',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Receta de la visita'),
        ),
    ]
