# Generated by Django 4.2.4 on 2023-12-27 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0014_alter_seguimiento_receta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='sede_org',
            new_name='id_sede_org',
        ),
    ]
