# Generated by Django 4.2.4 on 2023-12-29 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adopciones', '0015_rename_sede_org_mascota_id_sede_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPagoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=50)),
                ('acc_type', models.CharField(choices=[('C', 'Cuenta corriente'), ('V', 'Cuenta vista'), ('A', 'Cuenta de ahorro')], max_length=50)),
                ('num_cuenta', models.CharField(max_length=50, verbose_name='Numero de la cuenta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='colecta',
            name='rut',
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(verbose_name='Cantidad')),
                ('num_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.datospagousuario', verbose_name='numero del pago')),
            ],
        ),
    ]
