# Generated by Django 4.2.4 on 2023-12-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0016_datospagousuario_remove_colecta_rut_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedeorganizacion',
            name='nombre_sede',
            field=models.CharField(default='Nombre por defecto', max_length=50, verbose_name='Nombre de la sede'),
        ),
    ]
