# Generated by Django 4.2.4 on 2023-12-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0018_mascota_estado_adopcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='img_mascota',
            field=models.ImageField(upload_to='media', verbose_name='Imagen de la mascota'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='logo_org',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Logo de la Organizacion'),
        ),
    ]
