# Generated by Django 4.2.4 on 2023-12-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0019_alter_imagen_img_mascota_alter_organizacion_logo_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colecta',
            name='monto_inicial',
        ),
        migrations.AddField(
            model_name='colecta',
            name='monto_final',
            field=models.IntegerField(default=100000, verbose_name='Monto a recaudar'),
        ),
        migrations.AddField(
            model_name='colecta',
            name='monto_recaudado',
            field=models.IntegerField(default=0, verbose_name='Monto recaudado'),
        ),
    ]
