# Generated by Django 4.2.4 on 2023-12-31 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0021_remove_datospagousuario_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(verbose_name='Cantidad')),
                ('num_cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adopciones.datospagousuario')),
            ],
        ),
    ]
