# Generated by Django 4.2.4 on 2023-12-31 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('d3_dpa_chile', '0002_alter_comuna_codigo_alter_provincia_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adopciones', '0024_remove_datospagousuario_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPagoUsuario',
            fields=[
                ('banco', models.CharField(max_length=50)),
                ('acc_type', models.CharField(choices=[('C', 'Cuenta corriente'), ('V', 'Cuenta vista'), ('A', 'Cuenta de ahorro')], max_length=50)),
                ('num_cuenta', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Numero de la cuenta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripcion de la mascota')),
                ('tamano', models.CharField(choices=[('S', 'Pequeño'), ('L', 'Grande'), ('M', 'Mediano')], default='S', max_length=25, verbose_name='Tamaño de la mascota')),
                ('soc_1', models.CharField(choices=[('S', 'Si'), ('N', 'No'), ('N/A', 'No se sabe')], default='N/A', max_length=25, verbose_name='Sociable con niños')),
                ('soc_2', models.CharField(choices=[('S', 'Si'), ('N', 'No'), ('N/A', 'No se sabe')], default='N/A', max_length=25, verbose_name='Sociable con perros')),
                ('soc_3', models.CharField(choices=[('S', 'Si'), ('N', 'No'), ('N/A', 'No se sabe')], default='N/A', max_length=25, verbose_name='Sociable con gatos')),
                ('edad_est', models.IntegerField(verbose_name='Edad estimada de la mascota')),
                ('estado_adopcion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('nombre_org', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre de la organizacion')),
                ('tipo_organizacion', models.CharField(max_length=50, verbose_name='Tipo de Organizacion')),
                ('logo_org', models.ImageField(blank=True, upload_to='media', verbose_name='Logo de la Organizacion')),
                ('correo', models.CharField(default='correodefault@gmail.com', max_length=50, verbose_name='Correo de contacto de la organizacion')),
                ('contacto', models.CharField(default='+569', max_length=25, verbose_name='Telefono de contacto de la organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha del seguimiento')),
                ('centro_veterinario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Centro veterinario')),
                ('medico_veterinario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Medico veterinario')),
                ('diagnostico', models.TextField(verbose_name='Diagnostico del seguimiento')),
                ('receta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Receta de la visita')),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('tipo_nombre', models.CharField(choices=[('P', 'Perro'), ('G', 'Gato'), ('O', 'Otro')], max_length=10, primary_key=True, serialize=False, verbose_name='Tipo de mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='RUT')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, verbose_name='Género')),
                ('role', models.CharField(choices=[('A', 'Adoptante'), ('O', 'Organizacion')], default='A', max_length=10, verbose_name='Rol de usuario')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d3_dpa_chile.comuna')),
                ('nombre_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopciones.organizacion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Verificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ver', models.CharField(choices=[('O', 'Online'), ('P', 'Presencial')], max_length=20)),
                ('descripcion', models.TextField(verbose_name='Descripcion de la verificacion')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de la verificacion')),
                ('vigencia_animal', models.BooleanField(blank=True, null=True, verbose_name='Debe ser devuelto o no')),
                ('nombre_org', models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='adopciones.organizacion', verbose_name='Nombre de la organizacion')),
                ('rut', models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='adopciones.usuario', verbose_name='RUT del dueño')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de Vacunacion')),
                ('tipo_vacuna', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de vacuna')),
                ('vigencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vigencia de la vacuna (meses o años)')),
                ('id_seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.seguimiento')),
            ],
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='rut',
            field=models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='adopciones.usuario', verbose_name='RUT del dueño'),
        ),
        migrations.CreateModel(
            name='SedeOrganizacion',
            fields=[
                ('nombre_sede', models.CharField(default='Nombre por defecto', max_length=50, primary_key=True, serialize=False, verbose_name='Nombre de la sede')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion de la sede')),
                ('contacto', models.CharField(default='+569', max_length=25, verbose_name='Telefono de contacto de la sede')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d3_dpa_chile.comuna')),
                ('nombre_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(verbose_name='Cantidad')),
                ('num_cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adopciones.datospagousuario')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='rut',
            field=models.ForeignKey(blank=True, max_length=12, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopciones.usuario', verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='sede_org',
            field=models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='adopciones.sedeorganizacion', verbose_name='Sede de la organizacion'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tipo_nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.tipomascota'),
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_mascota', models.ImageField(upload_to='media', verbose_name='Imagen de la mascota')),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Colecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_colecta', models.CharField(max_length=50, verbose_name='Nombre de la colecta')),
                ('descripcion_colecta', models.TextField(verbose_name='Descripcion de la colecta')),
                ('banco', models.CharField(max_length=50)),
                ('acc_type', models.CharField(choices=[('C', 'Cuenta corriente'), ('V', 'Cuenta vista'), ('A', 'Cuenta de ahorro')], max_length=50)),
                ('num_cuenta', models.CharField(max_length=50, verbose_name='Numero de la cuenta')),
                ('monto_recaudado', models.IntegerField(default=0, verbose_name='Monto recaudado')),
                ('monto_final', models.IntegerField(default=100000, verbose_name='Monto a recaudar')),
                ('nombre_org', models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='adopciones.organizacion', verbose_name='Nombre de la organizacion')),
            ],
        ),
    ]
