# Generated by Django 4.2.4 on 2024-01-01 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0025_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificacion',
            name='nombre_org',
        ),
        migrations.AddField(
            model_name='verificacion',
            name='id_mascota',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='adopciones.mascota'),
        ),
    ]
