# Generated by Django 4.2.4 on 2024-01-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0026_remove_verificacion_nombre_org_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificacion',
            name='vigencia_animal',
        ),
    ]
